# Задание 1 

Задайте матрицу А=$\left( \begin{matrix}
   3.25 & -1.07 & 2.34  \\
   10.1 & 0.25 & -4.78  \\
   5.04 & -7.79 & 3.31  \\
\end{matrix} \right)$


In [24]:
import numpy as np
A = np.array([[3.25,-1.07,2.34],[10.1,0.25,-4.78],[5.04,-7.79,3.31]])

print(A)

[[ 3.25 -1.07  2.34]
 [10.1   0.25 -4.78]
 [ 5.04 -7.79  3.31]]


# Задание 2

Найти матрицу, обратную к A.

In [7]:
A_inv=np.linalg.inv(A)

print(A_inv)

[[ 0.14931587  0.0602325  -0.01857636]
 [ 0.23590453  0.00424915 -0.16063614]
 [ 0.32783815 -0.08171327 -0.04765278]]


# Задание 3 

Сгенерируйте матрицу В размером 3х3 со случайными элементами, равномерно распределенными на интервале от 0 до 1.

In [6]:
B=np.random.rand(3,3)

print(B)

[[0.65617681 0.90511505 0.51679386]
 [0.61676053 0.60173816 0.51123973]
 [0.49333024 0.06068646 0.14690739]]


# Задание 4

Выполните действия: $A+10\cdot B$, $A\cdot B$, ${{B}^{T}}$. 

In [9]:
result_1=A+10*B
result_2=np.dot(A,B)
result_3=B.T

print(result_1)
print(result_2)
print(result_3)

[[ 9.81176807  7.98115049  7.50793856]
 [16.2676053   6.2673816   0.3323973 ]
 [ 9.97330239 -7.18313537  4.77907386]]
[[ 2.62703362  2.4397704   1.4763168 ]
 [ 4.42345735  9.00201525  4.64521057]
 [ 0.13548967  0.07511177 -0.89165302]]
[[0.65617681 0.61676053 0.49333024]
 [0.90511505 0.60173816 0.06068646]
 [0.51679386 0.51123973 0.14690739]]


# Задание 5

Расположите элементы  матрицы А по возрастанию (по столбцам), определите максимальный и минимальный элементы  матрицы В, вычислите определитель матрицы В.

In [10]:
A_sorted=np.sort(A,axis=0)
max_B=np.max(B)
min_B=np.min(B)
det_B=np.linalg.det(B)

print(A_sorted)
print(max_B)
print(min_B)
print(det_B)

[[ 3.25 -7.79 -4.78]
 [ 5.04 -1.07  2.34]
 [10.1   0.25  3.31]]
0.9051150494078599
0.060686462920323314
0.049847317986709536


# Задание 6

Найти:$D=\sin (A)+{{B}^{3/5}}$

In [23]:
D=(np.sin(A))+(B**(3/5))

print(D)

[[ 0.66843194  0.0647374   1.39142658]
 [ 0.12321936  0.98470447  1.66632816]
 [-0.29235448 -0.81180728  0.14878006]]


# Задание 7

Задать массив С, используя операцию индексации и функцию ones:
$\left( \begin{matrix}
   1  \\
   2.94  \\
   -2.2  \\
   0.1   \\   
\end{matrix} \right)$

In [28]:
C=np.ones((4,1))
C[1]=2.94
C[2]=-2.2
C[3]=0.1

print(C)

[[ 1.  ]
 [ 2.94]
 [-2.2 ]
 [ 0.1 ]]


# Задание 8

Для двух векторов:
С и b= {0.6; 3.2; -1.8, 0.05} найти меру косинусного сходства.


In [29]:
b=np.array([0.6, 3.2, -1.8, 0.05])
cosin_sim=np.dot(b, C) / (np.linalg.norm(b)*np.linalg.norm(C))

print(cosin_sim)

[0.98649357]
